// Formulaire de géométrie : spécialité mathématiques (Première et Terminale) + compléments.
import { fr, rt } from './analysis.js';
const I = s => `<i>${s}</i>`, sup = s => `<sup>${s}</sup>`, sb = s => `<sub>${s}</sub>`;
const vec = s => `<span class="vc">${s}</span>`;
const AB = vec('AB');

export const FORMULARY = [
  { id: 'espace-vecteurs', title: 'Vecteurs de l’espace', level: 'Terminale', items: [
    { n: 'Coordonnées d’un vecteur', f: `${AB}(${I('x')}${sb('B')} − ${I('x')}${sb('A')} ; ${I('y')}${sb('B')} − ${I('y')}${sb('A')} ; ${I('z')}${sb('B')} − ${I('z')}${sb('A')})`, cmd: 'u=Vecteur(A,B)' },
    { n: 'Norme et distance', f: `‖${vec('u')}‖ = ${rt(`${I('x')}${sup(2)} + ${I('y')}${sup(2)} + ${I('z')}${sup(2)}`)}  ;  AB = ‖${AB}‖`, cmd: 'Distance(A,B)' },
    { n: 'Milieu de [AB]', f: `I(${fr(`${I('x')}${sb('A')} + ${I('x')}${sb('B')}`, '2')} ; ${fr(`${I('y')}${sb('A')} + ${I('y')}${sb('B')}`, '2')} ; ${fr(`${I('z')}${sb('A')} + ${I('z')}${sb('B')}`, '2')})`, cmd: 'I=Milieu(A,B)' },
    { n: 'Relation de Chasles', f: `${vec('AB')} + ${vec('BC')} = ${vec('AC')}` },
    { n: 'Colinéarité', f: `${vec('u')} et ${vec('v')} colinéaires ⇔ ∃ ${I('k')} ∈ ℝ, ${vec('u')} = ${I('k')}${vec('v')}`, note: 'A, B, C alignés ⇔ AB et AC colinéaires.', cmd: 'Colinéaires(u,v)' },
    { n: 'Combinaison linéaire, coplanarité', f: `${vec('u')}, ${vec('v')}, ${vec('w')} coplanaires ⇔ ∃ (α, β), ${vec('w')} = α${vec('u')} + β${vec('v')}`, note: 'Si u et v ne sont pas colinéaires.' , cmd: 'Coplanaires(u,v,w)' },
    { n: 'Base et repère', f: `(${vec('i')}, ${vec('j')}, ${vec('k')}) base de l’espace ⇔ vecteurs non coplanaires ; tout ${vec('u')} = ${I('x')}${vec('i')} + ${I('y')}${vec('j')} + ${I('z')}${vec('k')} de façon unique`, note: 'Repère (O ; i, j, k) : M(x ; y ; z) ⇔ OM = x·i + y·j + z·k.', cmd: 'Base(A,u,v,w)' },
    { n: 'Barycentre', f: `G = bar{(A, ${I('a')}), (B, ${I('b')})} ⇔ ${I('a')}${vec('GA')} + ${I('b')}${vec('GB')} = ${vec('0')},  ${I('x')}${sb('G')} = ${fr(`${I('a')}${I('x')}${sb('A')} + ${I('b')}${I('x')}${sb('B')}`, `${I('a')} + ${I('b')}`)}`, cmd: 'G=Barycentre(A,2,B,1)' },
  ] },
  { id: 'espace-droites-plans', title: 'Droites et plans de l’espace', level: 'Terminale', items: [
    { n: 'Représentation paramétrique d’une droite', f: `M ∈ 𝒟 ⇔ ${vec('AM')} = ${I('t')}${vec('u')} ⇔ { ${I('x')} = ${I('x')}${sb('A')} + ${I('t')}${I('a')} ; ${I('y')} = ${I('y')}${sb('A')} + ${I('t')}${I('b')} ; ${I('z')} = ${I('z')}${sb('A')} + ${I('t')}${I('c')} },  ${I('t')} ∈ ℝ`, note: 'u(a ; b ; c) vecteur directeur.', cmd: 'd=Droite(A,u)' },
    { n: 'Plan défini par un point et deux vecteurs', f: `M ∈ 𝒫 ⇔ ${vec('AM')} = ${I('s')}${vec('u')} + ${I('t')}${vec('v')}  (u, v non colinéaires)`, cmd: 'P: Plan(A,u,v)' },
    { n: 'Représentation paramétrique d’un plan', f: `{ ${I('x')} = ${I('x')}${sb('A')} + ${I('s')}${I('a')} + ${I('t')}${I('a′')} ; ${I('y')} = ${I('y')}${sb('A')} + ${I('s')}${I('b')} + ${I('t')}${I('b′')} ; ${I('z')} = ${I('z')}${sb('A')} + ${I('s')}${I('c')} + ${I('t')}${I('c′')} }` },
    { n: 'Équation cartésienne d’un plan', f: `${I('a')}${I('x')} + ${I('b')}${I('y')} + ${I('c')}${I('z')} + ${I('d')} = 0,  ${vec('n')}(${I('a')} ; ${I('b')} ; ${I('c')}) ≠ ${vec('0')} normal`, note: 'Plan de normale n passant par A : n·AM = 0.', cmd: 'P: 2x+y-z=3' },
    { n: 'Plan passant par A de vecteur normal n', f: `${I('a')}(${I('x')} − ${I('x')}${sb('A')}) + ${I('b')}(${I('y')} − ${I('y')}${sb('A')}) + ${I('c')}(${I('z')} − ${I('z')}${sb('A')}) = 0`, cmd: 'P=Plan(A,n)' },
    { n: 'Droite / droite', f: `coplanaires : parallèles (u, v colinéaires) ou sécantes ; sinon non coplanaires`, note: 'Sécantes : le système A + t·u = B + s·v a une unique solution.', cmd: 'Intersection(d1,d2)' },
    { n: 'Droite / plan', f: `𝒟 ∥ 𝒫 ⇔ ${vec('u')}·${vec('n')} = 0  (contenue si en plus A ∈ 𝒫) ; sinon sécants en un point`, cmd: 'Intersection(d,P)' },
    { n: 'Plan / plan', f: `parallèles ⇔ ${vec('n')} et ${vec('n′')} colinéaires ; sinon sécants selon une droite`, cmd: 'Intersection(P,Q)' },
  ] },
  { id: 'orthogonalite', title: 'Orthogonalité et distances (espace)', level: 'Terminale', items: [
    { n: 'Produit scalaire dans l’espace', f: `${vec('u')}·${vec('v')} = ${I('xx′')} + ${I('yy′')} + ${I('zz′')} = ‖${vec('u')}‖‖${vec('v')}‖cos θ`, cmd: 'u*v' },
    { n: 'Orthogonalité de deux vecteurs', f: `${vec('u')} ⊥ ${vec('v')} ⇔ ${vec('u')}·${vec('v')} = 0`, cmd: 'Orthogonaux(u,v)' },
    { n: 'Droites orthogonales', f: `𝒟 ⊥ 𝒟′ ⇔ ${vec('u')}·${vec('v')} = 0`, note: 'Pas nécessairement sécantes.' },
    { n: 'Droite orthogonale à un plan', f: `𝒟 ⊥ 𝒫 ⇔ ${vec('u')} colinéaire à ${vec('n')} ⇔ ${vec('u')} orthogonal à deux vecteurs non colinéaires du plan`, cmd: 'd=Perpendiculaire(A,P)' },
    { n: 'Plans perpendiculaires', f: `𝒫 ⊥ 𝒫′ ⇔ ${vec('n')}·${vec('n′')} = 0` },
    { n: 'Projeté orthogonal sur un plan', f: `H = M − ${fr(`${I('a')}${I('x')}${sb('M')} + ${I('b')}${I('y')}${sb('M')} + ${I('c')}${I('z')}${sb('M')} + ${I('d')}`, `${I('a')}${sup(2)} + ${I('b')}${sup(2)} + ${I('c')}${sup(2)}`)}·${vec('n')}`, note: 'H ∈ 𝒫 et MH colinéaire à n.', cmd: 'H=Projeté(M,P)' },
    { n: 'Distance d’un point à un plan', f: `d(M, 𝒫) = MH = ${fr(`|${I('a')}${I('x')}${sb('M')} + ${I('b')}${I('y')}${sb('M')} + ${I('c')}${I('z')}${sb('M')} + ${I('d')}|`, rt(`${I('a')}${sup(2)} + ${I('b')}${sup(2)} + ${I('c')}${sup(2)}`))}`, cmd: 'Distance(M,P)' },
    { n: 'Projeté orthogonal sur une droite', f: `H = A + ${fr(`${vec('AM')}·${vec('u')}`, `‖${vec('u')}‖${sup(2)}`)}${vec('u')}`, note: 'H ∈ 𝒟 et MH ⊥ u. Le projeté minimise la distance.', cmd: 'H=Projeté(M,d)' },
    { n: 'Distance d’un point à une droite', f: `d(M, 𝒟) = MH = ‖${vec('AM')} − ${fr(`${vec('AM')}·${vec('u')}`, `‖${vec('u')}‖${sup(2)}`)}${vec('u')}‖`, cmd: 'Distance(M,d)' },
    { n: 'Inégalité de Cauchy-Schwarz', f: `|${vec('u')}·${vec('v')}| ≤ ‖${vec('u')}‖‖${vec('v')}‖` },
    { n: 'Angle de deux vecteurs', f: `cos θ = ${fr(`${vec('u')}·${vec('v')}`, `‖${vec('u')}‖‖${vec('v')}‖`)}`, cmd: 'Angle(u,v)' },
  ] },
  { id: 'spheres', title: 'Sphères et cercles', level: 'Complément', items: [
    { n: 'Équation de sphère', f: `(${I('x')} − ${I('a')})${sup(2)} + (${I('y')} − ${I('b')})${sup(2)} + (${I('z')} − ${I('c')})${sup(2)} = ${I('r')}${sup(2)}`, cmd: 'S: (x-1)^2+(y-2)^2+(z-3)^2=9' },
    { n: 'Sphère de diamètre [AB]', f: `M ∈ 𝒮 ⇔ ${vec('MA')}·${vec('MB')} = 0 ⇔ (${I('x')} − ${I('x')}${sb('A')})(${I('x')} − ${I('x')}${sb('B')}) + (${I('y')} − ${I('y')}${sb('A')})(${I('y')} − ${I('y')}${sb('B')}) + (${I('z')} − ${I('z')}${sb('A')})(${I('z')} − ${I('z')}${sb('B')}) = 0` },
    { n: 'Plan tangent en A', f: `${vec('ΩA')}·${vec('AM')} = 0` },
    { n: 'Intersection droite / sphère', f: `substituer la représentation paramétrique : équation du 2ᵉ degré en ${I('t')} (0, 1 ou 2 points)`, cmd: 'Intersection(d,S)' },
    { n: 'Intersection plan / sphère', f: `cercle de centre H (projeté de Ω) et de rayon ${rt(`${I('r')}${sup(2)} − Ω${I('H')}${sup(2)}`)}`, cmd: 'Intersection(P,S)' },
  ] },
  { id: 'scalaire-plan', title: 'Produit scalaire (plan)', level: 'Première', items: [
    { n: 'Définition par le cosinus', f: `${vec('u')}·${vec('v')} = ‖${vec('u')}‖ × ‖${vec('v')}‖ × cos(${vec('u')}, ${vec('v')})` },
    { n: 'Expression analytique', f: `${vec('u')}(${I('x')} ; ${I('y')}),  ${vec('v')}(${I('x′')} ; ${I('y′')}) :  ${vec('u')}·${vec('v')} = ${I('xx′')} + ${I('yy′')}` },
    { n: 'Polarisation', f: `${vec('u')}·${vec('v')} = ${fr('1', '2')}(‖${vec('u')} + ${vec('v')}‖${sup(2)} − ‖${vec('u')}‖${sup(2)} − ‖${vec('v')}‖${sup(2)}) = ${fr('1', '2')}(‖${vec('u')}‖${sup(2)} + ‖${vec('v')}‖${sup(2)} − ‖${vec('u')} − ${vec('v')}‖${sup(2)})` },
    { n: 'Projeté orthogonal', f: `${vec('AB')}·${vec('AC')} = ${vec('AB')}·${vec('AH')}  (H projeté orthogonal de C sur (AB))`, note: 'Égal à AB × AH si même sens, −AB × AH sinon.' },
    { n: 'Orthogonalité', f: `${vec('u')} ⊥ ${vec('v')} ⇔ ${vec('u')}·${vec('v')} = 0` },
    { n: 'Propriétés', f: `${vec('u')}·${vec('v')} = ${vec('v')}·${vec('u')} ;  ${vec('u')}·(${vec('v')} + ${vec('w')}) = ${vec('u')}·${vec('v')} + ${vec('u')}·${vec('w')} ;  (${I('k')}${vec('u')})·${vec('v')} = ${I('k')}(${vec('u')}·${vec('v')})` },
    { n: 'Identités remarquables', f: `‖${vec('u')} + ${vec('v')}‖${sup(2)} = ‖${vec('u')}‖${sup(2)} + 2${vec('u')}·${vec('v')} + ‖${vec('v')}‖${sup(2)}` },
    { n: 'Théorème d’Al-Kashi', f: `BC${sup(2)} = AB${sup(2)} + AC${sup(2)} − 2·AB·AC·cos Â` },
    { n: 'Théorème de la médiane', f: `MA${sup(2)} + MB${sup(2)} = 2·MI${sup(2)} + ${fr('AB' + sup(2), '2')}  (I milieu de [AB])` },
    { n: 'Loi des sinus et aire', f: `${fr('a', 'sin Â')} = ${fr('b', 'sin B̂')} = ${fr('c', 'sin Ĉ')} = 2R ;  𝒜 = ${fr('1', '2')}·${I('bc')}·sin Â` },
    { n: 'Ensemble {M : MA·MB = 0}', f: `cercle de diamètre [AB]` },
  ] },
  { id: 'droites-plan', title: 'Droites et cercles du plan', level: 'Première', items: [
    { n: 'Équation cartésienne', f: `${I('a')}${I('x')} + ${I('b')}${I('y')} + ${I('c')} = 0,  ${vec('n')}(${I('a')} ; ${I('b')}) normal,  ${vec('u')}(−${I('b')} ; ${I('a')}) directeur`, cmd: 'd: 2x+3y=6' },
    { n: 'Équation réduite', f: `${I('y')} = ${I('m')}${I('x')} + ${I('p')},  ${I('m')} = ${fr(`${I('y')}${sb('B')} − ${I('y')}${sb('A')}`, `${I('x')}${sb('B')} − ${I('x')}${sb('A')}`)}` },
    { n: 'Droite de normale n passant par A', f: `${I('a')}(${I('x')} − ${I('x')}${sb('A')}) + ${I('b')}(${I('y')} − ${I('y')}${sb('A')}) = 0` },
    { n: 'Parallélisme, orthogonalité', f: `𝒟 ∥ 𝒟′ ⇔ ${I('ab′')} − ${I('a′b')} = 0 ;  𝒟 ⊥ 𝒟′ ⇔ ${I('aa′')} + ${I('bb′')} = 0  (⇔ ${I('mm′')} = −1)` },
    { n: 'Distance point-droite', f: `d(M, 𝒟) = ${fr(`|${I('a')}${I('x')}${sb('M')} + ${I('b')}${I('y')}${sb('M')} + ${I('c')}|`, rt(`${I('a')}${sup(2)} + ${I('b')}${sup(2)}`))}`, cmd: 'Distance(M,d)' },
    { n: 'Équation de cercle', f: `(${I('x')} − ${I('a')})${sup(2)} + (${I('y')} − ${I('b')})${sup(2)} = ${I('r')}${sup(2)}`, cmd: 'c: (x-1)^2+(y-2)^2=9' },
    { n: 'Cercle de diamètre [AB]', f: `(${I('x')} − ${I('x')}${sb('A')})(${I('x')} − ${I('x')}${sb('B')}) + (${I('y')} − ${I('y')}${sb('A')})(${I('y')} − ${I('y')}${sb('B')}) = 0` },
    { n: 'Colinéarité (plan)', f: `${vec('u')} et ${vec('v')} colinéaires ⇔ ${I('xy′')} − ${I('x′y')} = 0` },
    { n: 'Trigonométrie', f: `cos${sup(2)} θ + sin${sup(2)} θ = 1 ;  M(cos θ ; sin θ) sur le cercle trigonométrique` },
  ] },
  { id: 'mesures', title: 'Aires et volumes', level: 'Collège-Lycée', items: [
    { n: 'Cube', f: `𝒱 = ${I('a')}${sup(3)} ;  𝒜 = 6${I('a')}${sup(2)} ;  diagonale ${I('a')}${rt('3')}`, cmd: 'c1=Cube(A,3)' },
    { n: 'Pavé droit', f: `𝒱 = ${I('L')}${I('l')}${I('h')} ;  𝒜 = 2(${I('Ll')} + ${I('Lh')} + ${I('lh')})`, cmd: 'p1=Pavé(A,4,2,3)' },
    { n: 'Prisme, cylindre', f: `𝒱 = ${I('B')}·${I('h')} ;  cylindre : 𝒱 = π${I('r')}${sup(2)}${I('h')}, 𝒜 = 2π${I('r')}(${I('r')} + ${I('h')})`, cmd: 'cy=Cylindre(A,B,2)' },
    { n: 'Pyramide, cône', f: `𝒱 = ${fr('1', '3')}${I('B')}${I('h')} ;  cône : 𝒱 = ${fr('1', '3')}π${I('r')}${sup(2)}${I('h')}`, cmd: 'co=Cône(A,B,2)' },
    { n: 'Sphère, boule', f: `𝒜 = 4π${I('r')}${sup(2)} ;  𝒱 = ${fr('4', '3')}π${I('r')}${sup(3)}`, cmd: 'S=Sphère(A,2)' },
    { n: 'Tétraèdre régulier', f: `𝒱 = ${fr(`${I('a')}${sup(3)}`, `6${rt('2')}`)} ;  hauteur ${I('a')}${rt('2/3')}`, cmd: 'T=TétraèdreRégulier(A,3)' },
    { n: 'Relation d’Euler (polyèdre convexe)', f: `S − A + F = 2` },
  ] },
  { id: 'hors-programme', title: 'Outils utiles (hors programme)', level: 'Hors programme', items: [
    { n: 'Produit vectoriel', f: `${vec('u')} × ${vec('v')} = (${I('yz′')} − ${I('zy′')} ; ${I('zx′')} − ${I('xz′')} ; ${I('xy′')} − ${I('yx′')}) ;  ‖${vec('u')} × ${vec('v')}‖ = ‖${vec('u')}‖‖${vec('v')}‖ sin θ`, cmd: 'w=u×v' },
    { n: 'Déterminant 3×3 (volume algébrique)', f: `det(${vec('u')}, ${vec('v')}, ${vec('w')}) = ${vec('u')}·(${vec('v')} × ${vec('w')}) ;  𝒱 = |det|`, cmd: 'Déterminant(u,v,w)' },
    { n: 'Plan par trois points', f: `${vec('n')} = ${vec('AB')} × ${vec('AC')}`, cmd: 'P=Plan(A,B,C)' },
    { n: 'Distance point-droite (espace)', f: `d(M, 𝒟) = ${fr(`‖${vec('AM')} × ${vec('u')}‖`, `‖${vec('u')}‖`)}` },
    { n: 'Distance entre deux droites non coplanaires', f: `d = ${fr(`|${vec('AB')}·(${vec('u')} × ${vec('v')})|`, `‖${vec('u')} × ${vec('v')}‖`)}` },
    { n: 'Matrice de Gram (repère non orthonormé)', f: `${vec('u')}·${vec('v')} = ${I('X')}ᵀ·${I('G')}·${I('Y')},  ${I('G')} = (${vec('eᵢ')}·${vec('eⱼ')})`, note: 'Choisissez une base oblique dans l’onglet Repère.' },
  ] },
  { id: 'r4', title: 'Espace de dimension 4', level: 'Extension', items: [
    { n: 'Norme et distance dans ℝ⁴', f: `‖${vec('u')}‖ = ${rt(`${I('x')}${sup(2)} + ${I('y')}${sup(2)} + ${I('z')}${sup(2)} + ${I('w')}${sup(2)}`)} ;  AB = ‖${AB}‖`, cmd: 'Distance(A,B)' },
    { n: 'Produit scalaire dans ℝ⁴', f: `${vec('u')}·${vec('v')} = ${I('xx′')} + ${I('yy′')} + ${I('zz′')} + ${I('ww′')}` },
    { n: 'Droite de ℝ⁴', f: `M = A + ${I('t')}${vec('u')} :  4 équations paramétriques`, cmd: 'd=Droite(A,B)' },
    { n: 'Rotation dans le plan (x, w)', f: `${I('x′')} = ${I('x')}cos θ − ${I('w')}sin θ ;  ${I('w′')} = ${I('x')}sin θ + ${I('w')}cos θ` },
    { n: 'Projection en perspective sur ℝ³', f: `(${I('x')} ; ${I('y')} ; ${I('z')} ; ${I('w')}) ↦ ${fr('D', `D − ${I('w')}`)}·(${I('x')} ; ${I('y')} ; ${I('z')})`, note: 'D = distance du point de vue sur l’axe w.' },
    { n: 'Hypercube (tesseract)', f: `16 sommets, 32 arêtes, 24 faces, 8 cellules ;  S − A + F − C = 0 ;  hypervolume ${I('a')}${sup(4)} ;  diagonale 2${I('a')}`, cmd: 'T=Hypercube(O,2)' },
    { n: 'Pentachore (simplexe)', f: `5 sommets, 10 arêtes, 10 faces, 5 cellules`, cmd: 'T=Pentachore(O,2)' },
    { n: 'Hexadécachore', f: `8 sommets, 24 arêtes, 32 faces, 16 cellules`, cmd: 'T=Hexadécachore(O,2)' },
  ] },
];
